name: Playwright Tests with Allure Reports

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-login:
    runs-on: self-hosted
    name: Run login.spec.ts

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run login tests
        run: npx playwright test tests/login.spec.ts

      - name: Upload Allure Results (login)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results-login
          path: allure-results/
          retention-days: 30

  test-dashboard:
    runs-on: self-hosted
    name: Run dashboard.spec.ts

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run dashboard tests
        run: npx playwright test tests/dashboard.spec.ts

      - name: Upload Allure Results (dashboard)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results-dashboard
          path: allure-results/
          retention-days: 30

  publish-report:
    needs: [test-login, test-dashboard]
    runs-on: self-hosted
    permissions:
      contents: write

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Download Allure Results - login
        uses: actions/download-artifact@v4
        with:
          name: allure-results-login
          path: allure-results-login

      - name: Download Allure Results - dashboard
        uses: actions/download-artifact@v4
        with:
          name: allure-results-dashboard
          path: allure-results-dashboard

      - name: Combine Allure Results
        run: |
          mkdir combined-results
          copy allure-results-login/* combined-results/
          copy allure-results-dashboard/* combined-results/
        shell: powershell

      - name: Generate Allure Report
        run: npx allure generate ./combined-results --clean -o ./docs

      - name: Deploy Allure Report to GitHub Pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add docs
        shell: powershell

      - name: Commit Allure report if there are changes
        run: |
          if (git status --porcelain) {
            git commit -m "Update Allure report"
            git push origin gh-pages
          } else {
            Write-Output "No changes to commit"
          }
        shell: powershell